# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(585, 366)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        Main.setMinimumSize(QtCore.QSize(585, 361))
        Main.setMaximumSize(QtCore.QSize(585, 627))
        Main.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        Main.setAcceptDrops(True)
        Main.setWindowOpacity(0.9)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 230, 111, 71))
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(160, 230, 121, 71))
        self.toolButton.setObjectName("toolButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 10, 541, 192))
        self.graphicsView.setObjectName("graphicsView")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 22))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Main)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_words = QtWidgets.QAction(Main)
        self.actionSave_words.setObjectName("actionSave_words")
        self.actionExit = QtWidgets.QAction(Main)
        self.actionExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionExit.setObjectName("actionExit")
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionSave_words)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Book Analyse v.0.01 Alpha"))
        self.pushButton.setText(_translate("Main", "Analyse"))
        self.toolButton.setText(_translate("Main", "Save top words"))
        self.menuOpen.setTitle(_translate("Main", "File"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.actionOpen.setText(_translate("Main", "Open"))
        self.actionSave_words.setText(_translate("Main", "Save words"))
        self.actionExit.setText(_translate("Main", "Exit"))
